#!/bin/bash
#
# install.sh — IPFS service installer
#
# Generates cluster secret, optionally prompts for bootstrap peers,
# writes .env, and pulls docker images.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "=== IPFS Service Install ==="
echo ""

# Generate cluster secret if not already present
if [[ -f "$ENV_FILE" ]]; then
    source "$ENV_FILE"
fi

if [[ -z "$CLUSTER_SECRET" ]]; then
    echo "Generating IPFS Cluster secret..."
    CLUSTER_SECRET=$(od -vN 32 -An -tx1 /dev/urandom | tr -d ' \n')
    echo "  Generated: ${CLUSTER_SECRET:0:8}...(truncated)"
else
    echo "  Existing CLUSTER_SECRET found — keeping."
fi

# Replication factor
REPLICATION_FACTOR_MIN="${REPLICATION_FACTOR_MIN:-3}"
REPLICATION_FACTOR_MAX="${REPLICATION_FACTOR_MAX:-3}"

if command -v whiptail >/dev/null 2>&1; then
    REPLICATION_INPUT=$(whiptail --title "IPFS Cluster — Replication Factor" \
        --inputbox "Set replication factor (minimum copies per pin):" \
        8 60 "$REPLICATION_FACTOR_MIN" \
        3>&1 1>&2 2>&3) && REPLICATION_FACTOR_MIN="$REPLICATION_INPUT" || true
    REPLICATION_FACTOR_MAX="$REPLICATION_FACTOR_MIN"
fi

# Bootstrap peers
if [[ -z "$BOOTSTRAP_PEERS" ]]; then
    BOOTSTRAP_PEERS=""
fi

if command -v whiptail >/dev/null 2>&1; then
    BOOTSTRAP_INPUT=$(whiptail --title "IPFS Cluster — Bootstrap Peers" \
        --inputbox "Enter peer bootstrap multiaddresses (comma-separated ZeroTier IPs).\nLeave blank to skip bootstrap." \
        10 80 "$BOOTSTRAP_PEERS" \
        3>&1 1>&2 2>&3) && BOOTSTRAP_PEERS="$BOOTSTRAP_INPUT" || true
else
    echo "Enter peer bootstrap multiaddresses (comma-separated, blank to skip):"
    read -r BOOTSTRAP_PEERS
fi

# Write .env file
cat > "$ENV_FILE" <<EOF
# Generated by koad:io daemon configure — IPFS install.sh
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")

CLUSTER_SECRET=${CLUSTER_SECRET}
BOOTSTRAP_PEERS=${BOOTSTRAP_PEERS}
REPLICATION_FACTOR_MIN=${REPLICATION_FACTOR_MIN}
REPLICATION_FACTOR_MAX=${REPLICATION_FACTOR_MAX}
EOF

echo ""
echo "Configuration written to $ENV_FILE"
echo ""

# Pull docker images
echo "Pulling docker images..."
docker pull ipfs/kubo:latest
docker pull ipfs/ipfs-cluster:latest

echo ""
echo "=== IPFS install complete ==="
echo "Run 'koad-io daemon configure' and choose 'Start Services' to bring up the stack."
