github: [koad]
buymeacoffee: [koad]
BTC: 13VvGgHoSadwnjawxVJojPEzZqUzg6PM9b
AUR: Abbfc8oUJ5fwYEoxVAWUZYqustFaAd9uT7
LTC: LNtvSG48WVR8bWsDAhjrdbAkA7oK3wHkZn
EFL: LMjS8M5bjZ6SgCqkcUjPZi5CqwHq2d8EmW
CDN: CKyXmPGmjrAMY5uK46koHMVnkPCUsFqUkB