#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "=== Netbird Management Server Install ==="
echo ""

if [[ -f "$ENV_FILE" ]]; then
    source "$ENV_FILE"
fi

NETBIRD_DOMAIN="${NETBIRD_DOMAIN:-}"
NETBIRD_EMAIL="${NETBIRD_EMAIL:-}"

if command -v whiptail >/dev/null 2>&1; then
    DOMAIN_INPUT=$(whiptail --title "Netbird — Domain" \
        --inputbox "Domain for Netbird management server.\nDNS A record must already point to this machine." \
        10 70 "$NETBIRD_DOMAIN" \
        3>&1 1>&2 2>&3) && NETBIRD_DOMAIN="$DOMAIN_INPUT" || true

    EMAIL_INPUT=$(whiptail --title "Netbird — Let's Encrypt Email" \
        --inputbox "Email for Let's Encrypt TLS certificate:" \
        8 70 "$NETBIRD_EMAIL" \
        3>&1 1>&2 2>&3) && NETBIRD_EMAIL="$EMAIL_INPUT" || true
else
    echo "Domain for Netbird management (DNS must already resolve to this machine):"
    read -r NETBIRD_DOMAIN
    echo "Email for Let's Encrypt:"
    read -r NETBIRD_EMAIL
fi

if [[ -z "$NETBIRD_DOMAIN" ]] || [[ -z "$NETBIRD_EMAIL" ]]; then
    echo "ERROR: Domain and email are required."
    exit 1
fi

# Verify DNS resolves to this machine
RESOLVED_IP=$(dig +short "$NETBIRD_DOMAIN" 2>/dev/null | head -1)
MY_IP=$(curl -s ifconfig.me)

if [[ "$RESOLVED_IP" != "$MY_IP" ]]; then
    echo "WARNING: $NETBIRD_DOMAIN resolves to $RESOLVED_IP but this machine is $MY_IP"
    echo "Let's Encrypt will fail if DNS doesn't point here."
    if command -v whiptail >/dev/null 2>&1; then
        whiptail --title "DNS Mismatch" --yesno "Continue anyway?" 8 60 || exit 1
    else
        read -p "Continue anyway? (y/N) " -n 1 -r
        echo
        [[ $REPLY =~ ^[Yy]$ ]] || exit 1
    fi
fi

cat > "$ENV_FILE" <<EOF
# Generated by koad:io daemon configure — Netbird install.sh
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")

NETBIRD_DOMAIN=${NETBIRD_DOMAIN}
NETBIRD_EMAIL=${NETBIRD_EMAIL}
EOF

echo ""
echo "Configuration written to $ENV_FILE"
echo ""
echo "Running Netbird self-hosted installer..."

export NETBIRD_DOMAIN
export NETBIRD_LETSENCRYPT_EMAIL="$NETBIRD_EMAIL"
curl -fsSL https://github.com/netbirdio/netbird/releases/latest/download/getting-started.sh | bash

echo ""
echo "=== Netbird management server install complete ==="
echo "Dashboard: https://$NETBIRD_DOMAIN"
echo ""
echo "Generate a setup key for nodes:"
echo "  docker exec netbird-management /go/bin/netbird-mgmt setup-keys create --name kingdom --type reusable"
