#!/bin/bash

directory="./bundles/latest"

extension="js"
count=$(find $directory/*.$extension -type f | wc -l)
if [ "$count" -eq 1 ]; then
    file=$(find $directory/*.$extension -type f )
    echo "stitching in logic: $file"
    cp -f $file ./ext/logic.js
elif [ "$count" -eq 0 ]; then
    echo "No file found with extension $extension"
else
    echo "Multiple files found with extension $extension"
fi

extension="css"
count=$(find $directory/*.$extension -type f | wc -l)
if [ "$count" -eq 1 ]; then
    file=$(find $directory/*.$extension -type f )
    echo "stitching in stylesheets: $file"
    cp -f $file ./ext/styles.css
elif [ "$count" -eq 0 ]; then
    echo "No file found with extension $extension"
else
    echo "Multiple files found with extension $extension"
fi

echo "stitching in public folder..."
cp -rf ./src/public/* ./ext/