/**
 * koad:io-drive-chain — Shared Collections
 *
 * VESTA-SPEC-212 §3 (kingdom-state commitments), §6 (deposit/withdrawal semantics):
 * Minimongo collections for the drivechain package. Published via CacheBox DDP for
 * kingdom app consumption.
 *
 * Four collections:
 *   Sidechains              — Sidechain registry (one doc per sidechain)
 *   SidechainDeposits       — Deposit events (mainchain CDN → sidechain CDN)
 *   SidechainWithdrawals    — Withdrawal requests and bundles (sidechain → mainchain)
 *   KingdomSidechainState   — Daemon state persistence across restarts
 */

'use strict';

// ============================================================================
// Sidechains — Sidechain Registry
// ============================================================================
// One document per sidechain. Fields correspond to the sidechain configuration
// document (SPEC-212 §2.4) plus runtime state.
//
// Schema:
// {
//   _id:                      string   — auto-generated by Mongo
//
//   // Identity (SPEC-212 §2)
//   sidechain_id:             number   — uint16, allocated per SPEC-212 §2.1
//   kingdom_handle:           string   — kingdom slug (e.g., "koad", "copia")
//   kingdom_genesis_cid:      string   — CID of kingdom genesis record
//
//   // Lifecycle state (SPEC-212 §9)
//   state:                    string   — pending | active | frozen | terminating | terminated | migrating
//   created_at:               Date     — when the sidechain was allocated
//   genesis_block:            number   — first sidechain block height (0 = not yet genesis)
//   last_block:               number   — latest produced sidechain block height
//   last_block_hash:          string   — hex hash of latest sidechain block
//   last_mainchain_bmm_height: number  — CDN block height of last BMM commitment
//   terminated_at:            Date     — when sidechain was terminated (if applicable)
//
//   // Configuration (SPEC-212 §2.4)
//   block_time_seconds:       number   — sidechain block production interval
//   consensus:                string   — 'proof-of-authority' (v1) | 'open-mining' (v2)
//   block_producer:           string   — hex Ed25519 pubkey of current producer
//   backup_producers:         [string] — backup producer pubkeys
//   op_return_limit:          number   — OP_RETURN byte limit (default 80, extended 100)
//   fee_schedule: {
//     identity_op:            number   — fee for identity operations (default 0)
//     value_transfer:         number   — fee for value transfers
//     withdrawal:             number   — fee for withdrawal requests
//   }
//   withdrawal_period_blocks: number   — BIP 300 withdrawal fail period in mainchain blocks
//   min_workscore:            number   — MIN_WORKSCORE for BIP 301 BMM
//   mainchain:                string   — mainchain ticker (default 'CDN')
//   bip300_activation_height: number   — CDN block height for BIP 300 activation
//   bip301_activation_height: number   — CDN block height for BIP 301 activation
//   config_document_cid:      string   — CID of published sidechain configuration document
//
//   // Allocation (SPEC-212 §2.2)
//   allocation_bond_txid:     string   — txid of allocation bond deposit
//   allocated_by:             string   — 'cct' | 'koad' — allocation authority
//   allocated_at:             Date     — when the sidechain ID was allocated
//
//   // State commitment counters (SPEC-212 §3)
//   sigchain_tip_count:       number   — total entity sigchain tips committed
//   bond_attestation_count:   number   — total bond attestations committed
//   score_snapshot_count:     number   — total score snapshots committed
//   merkle_root_count:        number   — total merkle root commitments
//   last_merkle_root:         string   — hex SHA256 of last committed merkle root
//
//   // Operational
//   health:                   string   — 'healthy' | 'degraded' | 'down'
//   last_health_check:        Date     — when health was last verified
//   error_count:              number   — total errors encountered
//   last_error:               string   — last error message
//   updated_at:               Date     — last document update
// }
//
// SPEC-212 §3.1: Kingdom-state commitments include entity sigchain tips, trust bond
// attestations, kingdom merkle root, kingdom sovereign sigchain tip, and sidechain
// block producer identity.

Sidechains = new Mongo.Collection('drive_chain_sidechains');

// ============================================================================
// SidechainDeposits — Deposit Event Log
// ============================================================================
// Append-only log of deposit events (mainchain CDN → sidechain CDN).
// One document per deposit event, per SPEC-212 §6.1.
//
// Schema:
// {
//   _id:                      string   — auto-generated
//   sidechain_id:             number   — target sidechain ID
//
//   // Mainchain deposit transaction
//   mainchain_txid:           string   — CDN mainchain txid of deposit
//   mainchain_block:          number   — CDN block height of deposit
//   mainchain_confirmations:  number   — confirmations when processed
//   deposit_address:          string   — BIP 300 hashrate escrow address
//   deposit_amount_satoshi:   number   — amount deposited (in CDN satoshis)
//
//   // Sidechain credit
//   sidechain_address:        string   — credited sidechain address (SPEC-212 §6.3 derivation)
//   sidechain_txid:           string   — sidechain txid of credit issuance
//   sidechain_block:          number   — sidechain block where credit was issued
//
//   // Entity identity
//   entity_pubkey_hex:        string   — Ed25519 pubkey of depositor (if known)
//   entity_handle:            string   — entity name (denormalized)
//
//   // Status
//   status:                   string   — pending | credited | failed
//   failure_reason:           string   — if status = failed
//
//   // Metadata
//   created_at:               Date     — when deposit was detected
//   credited_at:              Date     — when sidechain credit was issued
//   processed_by:             string   — component that processed this deposit
// }
//
// SPEC-212 §6.1 step 3: sidechain issues equivalent CDN via sidechain UTXO.

SidechainDeposits = new Mongo.Collection('drive_chain_deposits');

// ============================================================================
// SidechainWithdrawals — Withdrawal Request Log
// ============================================================================
// Tracks withdrawal requests from sidechain members and the bundles submitted
// to CDN mainchain, per SPEC-212 §6.2.
//
// Two document types (distinguished by type field):
//   1. Single withdrawal request (type=request) — per-entity withdrawal
//   2. Withdrawal bundle (type=bundle) — aggregated set submitted to CDN
//
// Schema (type=request):
// {
//   _id:                      string   — auto-generated
//   type:                     string   — 'request'
//   sidechain_id:             number   — sidechain ID
//
//   // Requestor
//   entity_pubkey_hex:        string   — Ed25519 pubkey of requesting entity
//   entity_handle:            string   — entity name (denormalized)
//   sidechain_address:        string   — sidechain address burning from
//   mainchain_target_address: string   — CDN mainchain address receiving funds
//
//   // Withdrawal details
//   amount_satoshi:           number   — amount to withdraw
//   sidechain_txid:           string   — sidechain txid of withdrawal request
//   sidechain_block:          number   — sidechain block where request was included
//
//   // Bundle association
//   bundle_id:                string   — ID of the withdrawal bundle (if bundled)
//
//   // Status
//   status:                   string   — pending | bundled | submitted | fail_period | executed | failed | retrying
//   failure_reason:           string   — if status = failed
//
//   // Metadata
//   created_at:               Date     — when withdrawal was requested
//   bundled_at:               Date     — when bundled
//   executed_at:              Date     — when executed on mainchain
// }
//
// Schema (type=bundle):
// {
//   _id:                      string   — auto-generated
//   type:                     string   — 'bundle'
//   sidechain_id:             number   — sidechain ID
//
//   // Bundle content
//   bundle_cid:               string   — CID of the withdrawal bundle document
//   request_count:            number   — number of withdrawal requests in bundle
//   total_amount_satoshi:     number   — total CDN satoshis being withdrawn
//
//   // Mainchain submission
//   mainchain_txid:           string   — CDN txid of bundle submission
//   mainchain_block:          number   — CDN block height of submission
//   workscore:                number   — workscore of the submission (SPEC-212 §6.2)
//
//   // Fail period (SPEC-212 §6.2 step 3)
//   fail_period_start:        number   — CDN block height when fail period began
//   fail_period_end:          number   — CDN block height when fail period ends
//   fail_period_blocks:       number   — configured fail period length
//   challenged:               boolean  — whether a challenge was filed
//   challenge_txid:           string   — txid of challenge (if any)
//
//   // Result
//   status:                   string   — submitted | in_fail_period | challenged | executed | failed
//   execution_txid:           string   — CDN txid of execution (if executed)
//   execution_block:          number   — CDN block height of execution
//
//   // Metadata
//   submitted_at:             Date     — when bundle was submitted
//   executed_at:              Date     — when bundle was executed
//   created_by:               string   — component that created this bundle
// }
//
// SPEC-212 §6.2: withdrawal bundles aggregate multiple withdrawal requests and
// are subject to the BIP 300 fail period.

SidechainWithdrawals = new Mongo.Collection('drive_chain_withdrawals');

// ============================================================================
// KingdomSidechainState — Daemon Persistence
// ============================================================================
// Single-document state tracker for the drivechain package across restarts.
// One state document per watched sidechain (document key = sidechain_id).
//
// Schema:
// {
//   _id:                      string   — 'drivechain-state-<sidechain_id>'
//   sidechain_id:             number   — sidechain ID this state belongs to
//
//   // Operational status
//   status:                   string   — 'idle' | 'running' | 'error'
//   health:                   string   — 'healthy' | 'degraded' | 'down'
//
//   // Block tracking
//   last_indexed_mainchain:   number   — last CDN block height fully processed
//   last_produced_sidechain:  number   — last sidechain block height produced
//   last_bmm_height:          number   — last CDN height with BMM commitment
//   last_deposit_check:       number   — last CDN height checked for deposits
//
//   // Watch positions (SPEC-212 §8)
//   deposit_watch_from_block: number   — CDN block to start watching deposits from
//   withdrawal_check_upto:    number   — last checked CDN block for fail period expiry
//
//   // Counters
//   deposits_processed:       number   — total deposits processed
//   withdrawals_processed:    number   — total withdrawal bundles processed
//   bmm_commitments:          number   — total BMM commitments made
//   blocks_produced:          number   — total sidechain blocks produced
//   errors_encountered:       number   — total errors
//
//   // State for recovery
//   pending_deposits:         number   — deposits detected but not yet credited
//   pending_withdrawals:      number   — withdrawals in fail period
//
//   // Metadata
//   started_at:               Date     — when daemon last started
//   updated_at:               Date     — last state write
//   last_error:               string   — last error message
// }

KingdomSidechainState = new Mongo.Collection('drive_chain_state');

// ============================================================================
// NAMESPACED EXPORT OBJECT
// ============================================================================
// Top-level namespace for this package, consistent with Meteor 3 gotcha
// avoidance pattern (no globalThis collision).

KoadIoDriveChain = {
  name: 'KoadIoDriveChain',
  version: '0.0.1',

  // Collection references
  Sidechains,
  SidechainDeposits,
  SidechainWithdrawals,
  KingdomSidechainState,
};
