// session-token.js
//
// SPEC-196 §4 — MCP session token lifecycle in the extension context.
//
// The extension is a thin client. It holds no sovereign keys. Authentication
// to the daemon is via an MCP session token (a UUID generated by the extension
// and resolved by the daemon's session-file scan, same pattern as the pi and
// claude harnesses use).
//
// Lifecycle:
//   - On SW startup: pre-generate UUID, write to chrome.storage.session
//     (survives SW suspension; cleared on browser session end).
//   - All daemon HTTP requests include `Authorization: Bearer <token>`.
//   - On daemon 401: clear token, regenerate, retry once.
//   - On invalidation message from daemon (future — SPEC-196 §4.3): clear + regenerate.
//
// The session-storage choice is intentional. chrome.storage.local would persist
// across browser restarts, but the token is paired with a daemon-side session
// that won't survive a browser/daemon restart anyway. Session-storage gives us:
//   - survives SW wake/sleep cycles (the actual lifetime we care about)
//   - cleared on browser close → fresh token next session → fewer ghost sessions
//   - never persisted to disk → smaller exfiltration surface

const STORAGE_KEY = 'mcpSessionToken';

function generateUuid() {
	// crypto.randomUUID is available in MV3 service workers (Chrome 92+).
	return crypto.randomUUID();
}

async function getToken() {
	const stored = await chrome.storage.session.get(STORAGE_KEY);
	if (stored[STORAGE_KEY]) return stored[STORAGE_KEY];
	const token = generateUuid();
	await chrome.storage.session.set({ [STORAGE_KEY]: token });
	console.log('session-token: generated new MCP session token');
	return token;
}

async function clearToken() {
	await chrome.storage.session.remove(STORAGE_KEY);
	console.log('session-token: cleared');
}

async function rotateToken() {
	await clearToken();
	return getToken();
}

// Prime the token on SW startup so the first daemon request has it ready.
getToken().catch((err) => console.warn('session-token: prime failed', err));

export { getToken, clearToken, rotateToken };
