// Blob Encryption/Decryption — VESTA-SPEC-134 §5.2
// encryptBlob(plaintext, dek) → { ciphertext: Uint8Array (padded blob), iv: Uint8Array(12) }
// decryptBlob(ciphertext, dek) → Uint8Array (original plaintext bytes)
// wrapDEK(dek, kek) → wrapped_dek (base64url)
// unwrapDEK(wrapped_dek_b64u, kek) → dek CryptoKey
// generateDEK() → DEK CryptoKey
// padToSizeBucket(bytes) → padded Uint8Array
//
// SPEC REQUIREMENTS (non-negotiable per §5.2, §5.3):
// - Every encryptBlob call generates a fresh random 96-bit IV via crypto.getRandomValues
// - IV reuse with AES-GCM is catastrophic — it is never exposed to callers
// - Cleartext structure before encryption: [4-byte length prefix][plaintext]
//   (length prefix lets decryptor strip zero-padding from the plaintext)
// - Padding: zero-bytes appended after AES-GCM output; blob_size stored in UserMemories
// - AES-256-GCM for blob encryption; AES-KeyWrap (RFC 3394) for DEK wrapping
//
// Stored blob layout:
//   [4-byte actual_encrypted_len (big-endian)] [IV(12)] [AES-GCM-output] [zero_padding_to_bucket]
//   The 4-byte header lets decryptBlob strip zero-padding before feeding to subtle.decrypt.
//   This is implementation-level; the spec says "zero-bytes appended after auth_tag" which
//   is what this achieves — the auth_tag is the last bytes of AES-GCM-output.
//
// Cleartext structure (encrypted payload):
//   [4-byte plaintext_len prefix (big-endian)] [plaintext bytes] [optional zero padding]
//   The 4-byte prefix allows post-decrypt stripping of any plaintext-level padding (future use).

'use strict';

// ── Size bucket constants (SPEC-134 §5.3) ─────────────────────────────────────
// The spec table maps max_ciphertext_size → padded_size:
//   up to 3 KB  → 4 KB
//   up to 15 KB → 16 KB
//   up to 63 KB → 64 KB
//   up to 255 KB → 256 KB
//
// "Up to" is inclusive. Ciphertext > max goes to the next bucket.
// padToSizeBucket(bytes) finds the first bucket where max_size >= bytes.length.

const SIZE_BUCKETS = [
  { max: 3   * 1024, padded: 4   * 1024 },  //  ciphertext ≤ 3072  → 4 KB
  { max: 15  * 1024, padded: 16  * 1024 },  //  ciphertext ≤ 15360 → 16 KB
  { max: 63  * 1024, padded: 64  * 1024 },  //  ciphertext ≤ 64512 → 64 KB
  { max: 255 * 1024, padded: 256 * 1024 },  //  ciphertext ≤ 261120 → 256 KB
];

// ── generateDEK — random 256-bit AES-GCM key, not extractable ─────────────────

async function generateDEK() {
  return crypto.subtle.generateKey(
    { name: 'AES-GCM', length: 256 },
    true,   // extractable = true so it can be wrapped; wrapped form is opaque
    ['encrypt', 'decrypt']
  );
}

// ── padToSizeBucket ───────────────────────────────────────────────────────────
// Input: Uint8Array of ciphertext (IV || ciphertext || auth_tag).
// Output: Uint8Array padded with zeros to the nearest bucket size.
// The blob_size field in UserMemories stores the padded size.

function padToSizeBucket(bytes) {
  const len    = bytes.length;
  const bucket = SIZE_BUCKETS.find(b => b.max >= len);
  if (!bucket) {
    throw new Error(`padToSizeBucket: blob size ${len} bytes exceeds max bucket size (≤ 255 KB). Memory too large.`);
  }
  if (len === bucket.padded) return bytes; // already exact padded size
  const padded = new Uint8Array(bucket.padded);
  padded.set(bytes);
  // remaining bytes are zero by default (Uint8Array initialization)
  return padded;
}

// ── stripPadding ──────────────────────────────────────────────────────────────
// The first 4 bytes of the PLAINTEXT (before encryption) encode the real length
// of the plaintext as a big-endian uint32. After decryption, read those 4 bytes
// to know how many bytes of plaintext to extract (ignoring the plaintext padding).
// NOTE: This function operates on the DECRYPTED plaintext (with length prefix),
// not on the ciphertext.

function stripPadding(decryptedBytesWithPrefix) {
  if (decryptedBytesWithPrefix.length < 4) {
    throw new Error('stripPadding: buffer too short — missing 4-byte length prefix');
  }
  const view = new DataView(
    decryptedBytesWithPrefix.buffer,
    decryptedBytesWithPrefix.byteOffset,
    decryptedBytesWithPrefix.byteLength
  );
  const realLength = view.getUint32(0, false); // big-endian
  return decryptedBytesWithPrefix.slice(4, 4 + realLength);
}

// ── encryptBlob ───────────────────────────────────────────────────────────────
// plaintext: String or Uint8Array
// dek: CryptoKey (AES-256-GCM, extractable=true — generated by generateDEK)
// Returns: { ciphertext: Uint8Array (padded, IV || ciphertext || auth_tag), iv: Uint8Array(12) }
//
// CRITICAL: IV is generated INTERNALLY. Never expose IV generation to callers.
// This is the spec requirement (§5.2) — IV reuse is a protocol violation.

async function encryptBlob(plaintext, dek) {
  const plaintextBytes = typeof plaintext === 'string'
    ? new TextEncoder().encode(plaintext)
    : plaintext;

  // Cleartext structure per SPEC-134 §5.3: [4-byte big-endian plaintext_len][plaintext]
  // The 4-byte prefix allows post-decrypt stripping of padding.
  const cleartext = new Uint8Array(4 + plaintextBytes.length);
  const ctView = new DataView(cleartext.buffer);
  ctView.setUint32(0, plaintextBytes.length, false); // big-endian
  cleartext.set(plaintextBytes, 4);

  // Fresh random 96-bit IV — generated internally, never exposed to callers.
  // SPEC-134 §5.2: IV reuse is a protocol violation. IV is never exposed to callers.
  const iv = crypto.getRandomValues(new Uint8Array(12));

  const encrypted = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    dek,
    cleartext
  );

  // AES-GCM output = ciphertext || 16-byte auth_tag (appended automatically)
  const aesGcmOutput = new Uint8Array(encrypted);
  const actualEncryptedLen = aesGcmOutput.length;

  // Stored blob layout (before padding):
  //   [4-byte actual_encrypted_len] [IV(12)] [AES-GCM-output]
  //   The 4-byte header lets decryptBlob strip zero-padding before calling subtle.decrypt.
  const unpadded = new Uint8Array(4 + 12 + actualEncryptedLen);
  const blobView = new DataView(unpadded.buffer);
  blobView.setUint32(0, actualEncryptedLen, false);  // big-endian
  unpadded.set(iv, 4);
  unpadded.set(aesGcmOutput, 4 + 12);

  // Pad to nearest size bucket (SPEC-134 §5.3)
  const padded = padToSizeBucket(unpadded);

  return { ciphertext: padded, iv };
}

// ── decryptBlob ───────────────────────────────────────────────────────────────
// ciphertext: Uint8Array — padded blob from IPFS (IV || ciphertext || auth_tag || zero-padding)
// dek: CryptoKey (AES-256-GCM)
// Returns: Uint8Array (original plaintext bytes)

async function decryptBlob(ciphertext, dek) {
  // Minimum: 4-byte len header + 12-byte IV + 16-byte auth_tag (min AES-GCM output)
  if (!(ciphertext instanceof Uint8Array) || ciphertext.length < 32) {
    throw new Error('decryptBlob: ciphertext must be a Uint8Array of at least 32 bytes');
  }

  // Read the stored blob layout: [4-byte actual_encrypted_len][IV(12)][AES-GCM-output][padding]
  const blobView        = new DataView(ciphertext.buffer, ciphertext.byteOffset, ciphertext.byteLength);
  const actualEncryptedLen = blobView.getUint32(0, false);
  const iv              = ciphertext.slice(4, 4 + 12);
  const aesGcmData      = ciphertext.slice(4 + 12, 4 + 12 + actualEncryptedLen);

  let decrypted;
  try {
    decrypted = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv },
      dek,
      aesGcmData
    );
  } catch (err) {
    throw new Error('decryptBlob: AES-GCM decryption failed — wrong key or corrupted ciphertext');
  }

  // Strip the 4-byte plaintext length prefix per SPEC-134 §5.3
  return stripPadding(new Uint8Array(decrypted));
}

// ── wrapDEK ───────────────────────────────────────────────────────────────────
// dek: CryptoKey (AES-256-GCM, extractable)
// kek: CryptoKey (AES-KW — the sharedKnowledgeToken)
// Returns: base64url-encoded wrapped DEK string

async function wrapDEK(dek, kek) {
  const wrapped = await crypto.subtle.wrapKey(
    'raw',
    dek,
    kek,
    { name: 'AES-KW' }
  );
  return base64urlEncode(new Uint8Array(wrapped));
}

// ── unwrapDEK ─────────────────────────────────────────────────────────────────
// wrapped_dek_b64u: String (base64url-encoded wrapped DEK from UserMemories.wrapped_dek)
// kek: CryptoKey (AES-KW)
// Returns: CryptoKey (AES-256-GCM, extractable) or throws KEY_ROTATION_REQUIRED

async function unwrapDEK(wrapped_dek_b64u, kek) {
  let wrapped;
  try {
    wrapped = base64urlDecode(wrapped_dek_b64u);
  } catch (err) {
    throw new Error('unwrapDEK: invalid base64url encoding in wrapped_dek');
  }

  try {
    return await crypto.subtle.unwrapKey(
      'raw',
      wrapped,
      kek,
      { name: 'AES-KW' },
      { name: 'AES-GCM', length: 256 },
      true,  // extractable so it can be re-wrapped during KEK rotation
      ['encrypt', 'decrypt']
    );
  } catch (err) {
    // AES-KeyWrap failure on wrong key → key rotation required (SPEC-134 §6.4)
    throw new Error('KEY_ROTATION_REQUIRED: unwrapDEK failed — KEK is stale or DEK is corrupt');
  }
}

// ── base64url helpers ─────────────────────────────────────────────────────────

function base64urlEncode(bytes) {
  const base64 = typeof btoa !== 'undefined'
    ? btoa(String.fromCharCode(...bytes))
    : Buffer.from(bytes).toString('base64');
  return base64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
}

function base64urlDecode(str) {
  const base64 = str.replace(/-/g, '+').replace(/_/g, '/');
  const padded = base64 + '='.repeat((4 - base64.length % 4) % 4);
  if (typeof atob !== 'undefined') {
    const binary = atob(padded);
    return new Uint8Array([...binary].map(c => c.charCodeAt(0)));
  }
  return new Uint8Array(Buffer.from(padded, 'base64'));
}

// ── Exports ───────────────────────────────────────────────────────────────────

// SIZE_BUCKETS_PADDED: exported array of padded sizes for tests
const SIZE_BUCKETS_PADDED = SIZE_BUCKETS.map(b => b.padded);

if (typeof module !== 'undefined') {
  module.exports = {
    generateDEK,
    encryptBlob,
    decryptBlob,
    wrapDEK,
    unwrapDEK,
    padToSizeBucket,
    stripPadding,
    base64urlEncode,
    base64urlDecode,
    SIZE_BUCKETS,
    SIZE_BUCKETS_PADDED,
  };
}
