#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# profile create — generate a genesis sigchain entry and initial profile state
#
# Creates two entries:
#   1. koad.genesis  — anchors the chain, embeds the entity's Ed25519 public key
#   2. koad.state-update (scope:profile) — initial profile state (name, bio, etc.)
#
# Signs both entries with the entity's Ed25519 key ($ENTITY_DIR/id/ed25519).
# Publishes both to IPFS via `ipfs dag put`. Writes the tip CID to
# $ENTITY_DIR/var/sigchain-tip.
#
# Usage:
#   $ENTITY profile create [--name NAME] [--bio BIO] [--non-interactive]
#   koad profile create --name "Alice" --bio "A koad:io entity"
#
# Requires:
#   - ENTITY_DIR set (from koad:io env cascade)
#   - Ed25519 key at $ENTITY_DIR/id/ed25519 (private) + ed25519.pub (public)
#   - ipfs CLI available and daemon running (for dag put)
#   - node (for dag-json canonical serialization helper)

set -euo pipefail

ENTITY="${ENTITY:-koad}"
ENTITY_DIR="${ENTITY_DIR:-$HOME/.$ENTITY}"
KEY_PRIVATE="$ENTITY_DIR/id/ed25519"
KEY_PUBLIC="$ENTITY_DIR/id/ed25519.pub"
SIGCHAIN_TIP_FILE="$ENTITY_DIR/var/sigchain-tip"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Usage ─────────────────────────────────────────────────────────────────────

usage() {
  cat >&2 <<EOF
profile create — generate genesis sigchain entry + initial profile state

Usage:
  $ENTITY profile create [options]

Options:
  --name NAME           Display name (required in non-interactive mode)
  --bio BIO             Short bio (optional)
  --avatar CID          IPFS CID of your avatar image (optional)
  --non-interactive     Skip prompts; fail if required fields are missing
  -h, --help            Show this help

Creates:
  1. koad.genesis entry — anchors chain identity, embeds Ed25519 public key
  2. koad.state-update[scope:profile] entry — initial profile data

Both entries are signed with: $KEY_PRIVATE
Tip CID is written to: $SIGCHAIN_TIP_FILE

Prerequisites:
  - Ed25519 key pair at $ENTITY_DIR/id/ed25519{,.pub}
  - ipfs CLI available (daemon running for dag put)
  - node for canonical dag-json serialization

See also:
  $ENTITY profile update   — update existing profile
  $ENTITY profile publish  — push tip CID to canonical location
  $ENTITY profile view     — display current profile
EOF
}

# ── Arg parsing ───────────────────────────────────────────────────────────────

NAME=""
BIO=""
AVATAR=""
NON_INTERACTIVE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)           NAME="$2"; shift 2 ;;
    --bio)            BIO="$2";  shift 2 ;;
    --avatar)         AVATAR="$2"; shift 2 ;;
    --non-interactive) NON_INTERACTIVE=true; shift ;;
    -h|--help|help)   usage; exit 0 ;;
    *) echo "profile create: unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

# ── Pre-flight checks ─────────────────────────────────────────────────────────

if [[ ! -f "$KEY_PRIVATE" ]]; then
  echo "profile create: Ed25519 private key not found: $KEY_PRIVATE" >&2
  echo "Generate one with: ssh-keygen -t ed25519 -f $KEY_PRIVATE -P ''" >&2
  exit 1
fi

if [[ ! -f "$KEY_PUBLIC" ]]; then
  echo "profile create: Ed25519 public key not found: $KEY_PUBLIC" >&2
  exit 1
fi

if [[ -f "$SIGCHAIN_TIP_FILE" ]]; then
  echo "profile create: sigchain tip already exists: $SIGCHAIN_TIP_FILE" >&2
  echo "This entity already has a sigchain. Use '$ENTITY profile update' to update." >&2
  exit 1
fi

# ── Interactive prompts ───────────────────────────────────────────────────────

if [[ "$NON_INTERACTIVE" == false ]]; then
  if [[ -z "$NAME" ]]; then
    read -r -p "Display name [${ENTITY}]: " NAME
    NAME="${NAME:-$ENTITY}"
  fi
  if [[ -z "$BIO" ]]; then
    read -r -p "Short bio (optional): " BIO
  fi
  if [[ -z "$AVATAR" ]]; then
    read -r -p "Avatar IPFS CID (optional): " AVATAR
  fi
else
  if [[ -z "$NAME" ]]; then
    echo "profile create: --name is required in --non-interactive mode" >&2
    exit 1
  fi
fi

# ── Sign helper ───────────────────────────────────────────────────────────────
# Produces an Ed25519 signature over canonical dag-json pre-image.
# Outputs base64url without padding.
#
# TODO: Replace with a dedicated node script that:
#   1. Builds the canonical pre-image (dag-json, keys sorted, signature absent)
#   2. Signs with openssl pkeyutl -sign -rawin -inkey $KEY_PRIVATE
#   3. Encodes to base64url without padding
#   4. Outputs the full signed entry as canonical dag-json
#   5. Computes the CIDv1 (dag-json, sha2-256) of the final entry
#
# The openssl invocation per SPEC-111 §3.3:
#   printf '%s' "$PRE_IMAGE" | openssl pkeyutl -sign -rawin -inkey $KEY_PRIVATE \
#     | base64 -w0 | tr '+/' '-_' | tr -d '='
#
# NOTE: OpenSSL Ed25519 keys generated by ssh-keygen require conversion to
# PEM format first. Use:
#   ssh-keygen -p -m PEM -f $KEY_PRIVATE -N "" -q
# OR use a node script with @noble/ed25519 directly, reading the raw key bytes.

sign_entry() {
  local pre_image="$1"
  # TODO: implement canonical signing
  echo "TODO_SIGNATURE_$(echo -n "$pre_image" | sha256sum | cut -c1-16)"
}

# ── Build public key (base64url) ──────────────────────────────────────────────

# TODO: extract raw Ed25519 public key bytes from $KEY_PUBLIC and base64url-encode.
# ssh-keygen -e -m pkcs8 outputs PEM; extract raw 32-byte key from DER encoding.
# Simpler: use a node one-liner:
#   node -e "const fs=require('fs'); const k=fs.readFileSync('$KEY_PUBLIC','utf8');
#            // parse OpenSSH ed25519 public key → raw 32 bytes → base64url"

PUBKEY_B64URL="TODO_PUBKEY_BASE64URL"
echo "profile create: WARNING — public key extraction not implemented. See TODO in command.sh" >&2

mkdir -p "$ENTITY_DIR/var"

# ── Step 1: genesis entry ─────────────────────────────────────────────────────

echo "Creating genesis entry for $ENTITY..."

# TODO: replace with node script that:
#   - Builds the canonical pre-image JSON (keys sorted: entity,payload,previous,timestamp,type,version)
#   - Signs it per SPEC-111 §3.3
#   - Adds the signature field
#   - Runs: ipfs dag put --input-codec dag-json --store-codec dag-json < entry.json
#   - Captures and prints the returned CID

GENESIS_ENTRY=$(cat <<GENESIS
{
  "entity": "$ENTITY",
  "payload": {
    "created": "$TIMESTAMP",
    "description": "$ENTITY sovereign profile chain — genesis",
    "entity": "$ENTITY",
    "pubkey": "$PUBKEY_B64URL"
  },
  "previous": null,
  "signature": "$(sign_entry "genesis-pre-image-placeholder")",
  "timestamp": "$TIMESTAMP",
  "type": "koad.genesis",
  "version": 1
}
GENESIS
)

# TODO: pipe GENESIS_ENTRY to `ipfs dag put --input-codec dag-json --store-codec dag-json`
# GENESIS_CID=$(echo "$GENESIS_ENTRY" | ipfs dag put --input-codec dag-json --store-codec dag-json)
GENESIS_CID="TODO_GENESIS_CID"
echo "profile create: genesis entry CID: $GENESIS_CID (TODO: wire to ipfs dag put)" >&2

# ── Step 2: initial profile state-update entry ────────────────────────────────

echo "Creating initial profile state entry..."

PROFILE_ENTRY=$(cat <<PROFILE
{
  "entity": "$ENTITY",
  "payload": {
    "data": {
      "avatar": ${AVATAR:+"\"$AVATAR\""}${AVATAR:-null},
      "bio": "$BIO",
      "name": "$NAME",
      "socialProofs": []
    },
    "scope": "profile"
  },
  "previous": "$GENESIS_CID",
  "signature": "$(sign_entry "profile-pre-image-placeholder")",
  "timestamp": "$TIMESTAMP",
  "type": "koad.state-update",
  "version": 1
}
PROFILE
)

# TODO: pipe PROFILE_ENTRY to ipfs dag put
# PROFILE_CID=$(echo "$PROFILE_ENTRY" | ipfs dag put --input-codec dag-json --store-codec dag-json)
PROFILE_CID="TODO_PROFILE_CID"
echo "profile create: profile entry CID: $PROFILE_CID (TODO: wire to ipfs dag put)" >&2

# ── Write tip CID ─────────────────────────────────────────────────────────────

echo "$PROFILE_CID" > "$SIGCHAIN_TIP_FILE"
echo "profile create: tip CID written to $SIGCHAIN_TIP_FILE"

echo ""
echo "Profile created (scaffold — crypto not yet implemented):"
echo "  Entity:       $ENTITY"
echo "  Name:         $NAME"
echo "  Genesis CID:  $GENESIS_CID"
echo "  Profile CID:  $PROFILE_CID (tip)"
echo ""
echo "Next: $ENTITY profile publish  — announce tip CID to canonical location"
