/**
 * koad:io-scoring-indexer — Shared Collections
 *
 * ROOTY-SPEC-009 §7.3: Minimongo collections for the scoring indexer.
 * Published via CacheBox DDP for kingdom app consumption.
 *
 * Two collections:
 *   ScoreTable     — one document per scored entity, current scores
 *   ScoreHistory   — per-entity score snapshots over time (for storefront charts)
 *   ScoringIndexerState — daemon persistence across restarts
 */

'use strict';

// ============================================================================
// ScoreTable — Current Entity Scores
// ============================================================================
// One document per scored entity. Updated on every score recomputation
// (per block or per snapshot interval).
//
// Schema (per SPEC-009 §7.3):
// {
//   _id:                    string   — auto-generated by Mongo
//   entity_pubkey_hex:      string   — Ed25519 public key hex (unique identifier)
//   entity_name:            string   — human-readable entity name (from WatchedEntities)
//
//   // Total score
//   total_score:            number   — computed total × diversity bonus, [0, 1+b]
//   diversity_bonus:        number   — dataplane diversity multiplier (1.0–1.4)
//   dataplane_count:        number   — number of chains with activity
//
//   // Component scores (each [0, 1])
//   components: {
//     longevity:            number   — S_longevity
//     activity:             number   — S_activity
//     trust:                number   — S_trust
//     stake:                number   — S_stake
//     governance:           number   — S_governance
//   }
//
//   // Raw signals (for transparency / verification)
//   signals: {
//     first_seen_block:     number   — earliest block across all chains
//     last_seen_block:      number   — latest block across all chains
//     broadcast_count:      number   — total kIO broadcasts across all chains
//     bonded_count:         number   — unique outgoing bond edges
//     bonded_by_count:      number   — unique incoming bond edges
//     trust_propagation:    number   — 2-degree trust network size
//     total_stake_value:    number   — sum active timelock values
//     governance_actions:   number   — governance participation count
//   }
//
//   // Chain breakdown
//   chain_scores: {
//     BTC:                  Object   — per-chain component scores (optional)
//     LTC:                  Object
//     CDN:                  Object
//     AUR:                  Object
//     EFL:                  Object
//   }
//
//   // Metadata
//   rank:                   number   — ordinal rank (1-indexed, computed on publication)
//   last_updated_block:     number   — block height at last recomputation
//   last_updated_at:        Date     — when this record was updated
// }

ScoreTable = new Mongo.Collection('scoring_score_table');

// ============================================================================
// ScoreHistory — Per-Entity Score Snapshots
// ============================================================================
// Append-only log of score snapshots for each entity. Used by storefront
// score-over-time charts. A new document is inserted at each snapshot interval
// (default every 2016 blocks).
//
// Schema (per SPEC-009 §7.3):
// {
//   _id:                  string   — auto-generated
//   entity_pubkey_hex:    string   — entity identifier
//   entity_name:          string   — entity name (denormalized for query readability)
//
//   snapshot_block:       number   — block height at snapshot
//   snapshot_time:        Date     — block timestamp at snapshot
//
//   total_score:          number   — computed total score at snapshot time
//   components: {
//     longevity:          number   — S_longevity at snapshot
//     activity:           number   — S_activity at snapshot
//     trust:              number   — S_trust at snapshot
//     stake:              number   — S_stake at snapshot
//     governance:         number   — S_governance at snapshot
//   }
//
//   diversity_bonus:      number   — dataplane diversity bonus at snapshot
//   dataplane_count:      number   — chains active at snapshot
//
//   // Merkle proof (if this snapshot was anchored on-chain)
//   merkle_root:          string   — hex SHA256 Merkle root (32 bytes)
//   merkle_proof:         [string]  — hex sibling hashes for this leaf
//   snapshot_txid:        string   — txid of tag 0x14 broadcast (if anchored)
// }

ScoreHistory = new Mongo.Collection('scoring_score_history');

// ============================================================================
// ScoringIndexerState — Daemon Persistence
// ============================================================================
// Single-document state tracker for the scoring indexer across restarts.
//
// Schema:
// {
//   _id:                          'scoring-indexer-state'
//   status:                       string   — 'idle' | 'scanning' | 'watching' | 'error'
//
//   // Genesis scan tracking
//   genesis_complete:             boolean  — true if initial genesis scan finished
//   genesis_block:                number   — block height at genesis scan
//   genesis_entity_count:         number   — entities discovered during genesis
//   genesis_merkle_root:          string   — hex Merkle root of genesis snapshot
//   genesis_txid:                 string   — txid of genesis tag 0x14 broadcast
//
//   // Incremental tracking
//   last_indexed_block:           number   — last block fully processed
//   last_snapshot_block:          number   — last block at which snapshot was taken
//   last_snapshot_merkle_root:    string   — hex Merkle root of last snapshot
//   last_snapshot_txid:           string   — txid of last snapshot broadcast
//
//   // Entity tracking
//   entity_count:                 number   — current number of scored entities
//   entity_count_change:          number   — entities added since last snapshot
//
//   // Operational
//   scan_count:                   number   — total block scan cycles
//   snapshot_count:               number   — total snapshots produced
//   emitted_count:                number   — total daemon emissions fired
//   error_count:                  number   — total errors encountered
//   last_error:                   string   — last error message
//   started_at:                   Date     — when daemon last started
//   updated_at:                   Date     — last state write
// }

ScoringIndexerState = new Mongo.Collection('scoring_indexer_state');
